spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/nosa?useUnicode=true&characterEncoding=UTF8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: nosa
    password: qawsedrf1!
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**
    
mybatis:
  type-aliases-package: nosa.nns.dao
  mapper-locations: mybatis/mapper/**/*.xml